name: Docker Preview

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Get Current Commit SHA
        id: commit_sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t aiagt-web-preview:v${{ env.COMMIT_SHA }} .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag aiagt-web-preview:v${{ env.COMMIT_SHA }} $DOCKER_USERNAME/aiagt-web-preview:v${{ env.COMMIT_SHA }}
          docker tag aiagt-web-preview:v${{ env.COMMIT_SHA }} $DOCKER_USERNAME/aiagt-web-preview:latest
          docker push $DOCKER_USERNAME/aiagt-web-preview:v${{ env.COMMIT_SHA }}
          docker push $DOCKER_USERNAME/aiagt-web-preview:latest

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd aiagt/deploy
            sudo docker-compose -f docker-compose-web.yml pull
            sudo docker-compose -f docker-compose-web.yml up -d
          EOF