name: Docker Release

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Get Release Tag
        id: tag
        run: echo "TAG_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t aiagt-web:${{ env.TAG_VERSION }} .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag aiagt-web:${{ env.TAG_VERSION }} $DOCKER_USERNAME/aiagt-web:${{ env.TAG_VERSION }}
          docker tag aiagt-web:${{ env.TAG_VERSION }} $DOCKER_USERNAME/aiagt-web:latest
          docker push $DOCKER_USERNAME/aiagt-web:${{ env.TAG_VERSION }}
          docker push $DOCKER_USERNAME/aiagt-web:latest
